Jordan/Areas/Admin/Controllers/FeatureController.cs
using Core.Dto.ViewModel.Store.SubCategory;
using Core.Interface.Store;
using Core.Tools;
using Domain.Store;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using WebStore.Base;
using static Google.Protobuf.Compiler.CodeGeneratorResponse.Types;

namespace Personal.Areas.Admin.Controllers
{
    [Area(AreaNames.Admin)]
    public class FeatureController : BaseController
    {
        private readonly IFeature _feature;
        private readonly ISubcategory _subcategory;

        public FeatureController(IFeature feature, ISubcategory subcategory)
        {
            _feature = feature;
            _subcategory = subcategory;
        }

        public IActionResult Index()
        {
            return View(_feature.GetAll());
        }
        public IActionResult Create()
        {
            ViewBag.SubCategory = new SelectList(_subcategory.GetAllSubCategories(), "Id","SubCategoryName");
            return View();
        }

        // POST: RoleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Domain.Store.Feature feature)
        {


            if (!ModelState.IsValid)
            {
                ViewBag.SubCategory = new SelectList(_subcategory.GetAllSubCategories(), "Id", "SubCategoryName", feature.subCategoryId);
                return View(feature);
            }


            try
            {
              
                var result = _feature.Insert(feature);
                if (result != null)
                {
                    TempData[Success] = SuccessMessage;
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData[Error] = ErrorMessage;
                    ViewBag.SubCategory = new SelectList(_subcategory.GetAllSubCategories(), "Id", "SubCategoryName", feature.subCategoryId);
                    return View(feature);
                }
            }
            catch (Exception e)
            {
                TempData[Error] = ErrorMessage;
                ViewBag.SubCategory = new SelectList(_subcategory.GetAllSubCategories(), "Id", "SubCategoryName", feature.subCategoryId);
                return View(feature);
            }





        }

        // GET: RoleController/Edit/5
        public ActionResult Edit(int FeatureId)
        {

            var result = _feature.GetFeatureById(FeatureId);
            if (result == null)
            {
                return NotFound();
            }
            ViewBag.SubCategory = new SelectList(_subcategory.GetAllSubCategories(), "Id", "SubCategoryName", result.subCategoryId);
            return View(result);
        }

        // POST: RoleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Domain.Store.Feature Feature)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.SubCategory = new SelectList(_subcategory.GetAllSubCategories(), "Id", "SubCategoryName", Feature.subCategoryId);
                return View(Feature);
            }
            var result = _feature.Update(Feature);
            if (result != null)
            {
                TempData[Success] = SuccessMessage;
                return RedirectToAction("Index");
            }
            else
            {
                TempData[Error] = ErrorMessage;
                ViewBag.SubCategory = new SelectList(_subcategory.GetAllSubCategories(), "Id", "SubCategoryName",result.subCategoryId);
                return View(Feature);
            }

        }

        // GET: RoleController/Delete/5
        public ActionResult Delete(int id)
        {



            var obj = _feature.GetFeatureById(id);
            if (obj == null)
            {
                return NotFound();
            }

          

            var result = _feature.Delete(id);
            if (result)
            {
                TempData[Success] = SuccessMessage;
                return RedirectToAction("Index");
            }
            TempData[Error] = ErrorMessage;
            return RedirectToAction("Index");


        }
      
    }
}

Jordan/Areas/Admin/Controllers/FeatureValueController.cs
using AutoMapper;
using Core.Dto.ViewModel.Store.FeatureValueDto;
using Core.Dto.ViewModel.Store.ProductFeatureValue;
using Core.Interface.Store;
using Core.Tools;
using Domain.Store;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MySqlX.XDevAPI.Common;
using WebStore.Base;
using static Google.Protobuf.Compiler.CodeGeneratorResponse.Types;

namespace Personal.Areas.Admin.Controllers
{
    [Area(areaName:AreaNames.Admin)]
    public class FeatureValueController : BaseController
    {
        private readonly IFeatureValue _featureValue;
        private readonly IFeature _feature;
        private readonly IProduct _product;
        private readonly IProductFeatureValue _Productfeature;
        private readonly IMapper _mapper;

        public FeatureValueController(IFeatureValue featureValue, IFeature feature, IMapper mapper, IProductFeatureValue productfeature, IProduct product)
        {
            _featureValue = featureValue;
            _feature = feature;
            _mapper = mapper;
            _Productfeature = productfeature;
            _product = product;
        }

        public IActionResult Index(int FeatureId)
        {
            if (FeatureId == 0) {
                return NotFound();
            }
            var feature=_feature.GetFeatureById(FeatureId);
            if (feature == null)
            {
                return NotFound();
            }
            return View(new ShowFeatureValueVM()
            {
                feature= feature,
                FeatureValues=_featureValue.GetFeatureValueByfeatureId(FeatureId)
                
            });
        }
        [HttpGet]
        public IActionResult Create(int FeatureId)
        {
            if (FeatureId == 0)
            {
                return NotFound();
            }
            var feature = _feature.GetFeatureById(FeatureId);
            if (feature == null)
            {
                return NotFound();
            }

            return View(new FeatureValueAddVM()
            {
                FeatureId = FeatureId,
                FeatureTitle=feature.Title
                
            });
        }
        [HttpPost]
        public IActionResult Create(FeatureValueAddVM featureValue)
        {
            if (!ModelState.IsValid) {
                return View(featureValue);
            }
            string FilePAthThumb, FIleName, FilePAth = null;
            FIleName = FileTools.GetFileName(featureValue.ImageFile);
            FilePAth = FileTools.UploadFile(featureValue.ImageFile, FIleName, "featureValue");
            featureValue.Image=FilePAth;
            var result = _featureValue.Insert(new FeatureValue()
            {
                FeatureId = featureValue.FeatureId,
                Value = featureValue.Value,
                Image = FilePAth

            });
            
         
            if (result != null)
            {
                TempData[Success] = SuccessMessage;
                return RedirectToAction("Index", new { FeatureId =result.FeatureId});
            }
            else
            {
                TempData[Error] = ErrorMessage;
                FileTools.DeleteFile(FilePAth);
                return View("create", new { FeatureId =featureValue.FeatureId});
            }
          
        }
        [HttpGet]
        public IActionResult Edit(int featureValueId)
        {
            var featurevalue = _featureValue.GetFeatureValueById(featureValueId);
            if(featurevalue == null)
            {
                return NotFound();
            }
            var feature=_feature.GetFeatureById(featurevalue.FeatureId);

            return View(new FeatureValueEditVM()
            {
                FeatureId=featurevalue.FeatureId,
                FeatureTitle=feature.Title,
                Id=featurevalue.Id,
                Value=featurevalue.Value,
            });
        }
        [HttpPost]
        public IActionResult Edit(FeatureValueEditVM editVM)
        {
            if(!ModelState.IsValid)
            {
                return View(editVM);
            }
            var old=_featureValue.GetFeatureValueById(editVM.Id);   
            if (editVM.ImageFile != null) {
                string  FIleName, FilePAth = null;
                FIleName = FileTools.GetFileName(editVM.ImageFile);
                FilePAth = FileTools.UploadFile(editVM.ImageFile, FIleName, "featureValue");
                FileTools.DeleteFile(old.Image);
                old.Image = FilePAth;
            }
            old.Value = editVM.Value;
            var Result = _featureValue.Update(old);
            if (Result != null)
            {
                TempData[Success] = SuccessMessage;
                return RedirectToAction("Index", new { FeatureId = Result.FeatureId });
            }
            else
            {
                TempData[Error] = ErrorMessage;
                if (editVM.ImageFile != null)
                {
                    FileTools.DeleteFile(editVM.Image);
                }
                   
                return RedirectToAction("Edit", new { featureValueId = editVM.Id });
            }
        }
        public IActionResult ProductFeatureValue(int featureValueId)
        {
            var featureValue = _featureValue.GetFeatureValueById(featureValueId);
            if(featureValue==null)
            {
                return NotFound();
            }
            ViewBag.Product = new SelectList(_product.GetProductBySubcategory(featureValue.Feature.subCategoryId), "Id", "ProductName");
            var VM = new ShowProductFeatureValueVm()
            {
                FeatureValueId = featureValueId,
                FeatureValueTitle = featureValue.Value,
                products = _Productfeature.GetProductOfFeatureValuue(featureValueId)
            };
            return View(VM);
        }
        public IActionResult RemoveProductFromFeatureId(ProductFeatureValue featureValue)
        {
            var result = _Productfeature.Delete(featureValue);
            if (result)
            {
                TempData[Success] = SuccessMessage;
                return RedirectToAction("ProductFeatureValue", new
                {
                    featureValueId = featureValue.FeatureValueId
                });
            }
            else
            {
                TempData[Error] = ErrorMessage;

                return RedirectToAction("ProductFeatureValue", new
                {
                    featureValueId = featureValue.FeatureValueId
                });
            }

          
        }
      public IActionResult AddProductToFeatureValue(int FeatureValueId,int ProductId)
        {
            var exist=_Productfeature.CheckExist(FeatureValueId,ProductId);
            if (exist != null)
            {
                TempData[warning] = "این محصول در لیست موجود می باشد";
                return RedirectToAction("ProductFeatureValue", new
                {
                    featureValueId = FeatureValueId
                });
            }
            var result= _Productfeature.Insert(FeatureValueId,ProductId);
            if (result)
            {
                TempData[Success] = SuccessMessage;
                return RedirectToAction("ProductFeatureValue", new
                {
                    featureValueId = FeatureValueId
                });
            }
            else
            {
                TempData[Error] = ErrorMessage;
               
                return RedirectToAction("ProductFeatureValue", new
                {
                    featureValueId = FeatureValueId
                });
            }
            
        }
    }
}

Jordan/Areas/Admin/Views/Feature/Create.cshtml
@model Domain.Store.Feature

@{
    ViewData["Title"] = "Create";
}


<div class="col-md-12">
    <div class="card card-success">
        <div class="card-header">
            <h3 class="card-title">دسته بندی </h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-12 col-md-4">
                    <form asp-action="Create" id="myform">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        

                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>

                        </div>
                        <div class="form-group">
                            <label asp-for="subCategoryId" class="control-label"></label>
                            <select asp-for="subCategoryId" class="form-control" asp-items="ViewBag.SubCategory"></select>
                                <span asp-validation-for="subCategoryId" class="text-danger"></span>

                        </div>
                        

                        <div class="form-group">
                            <input type="submit" value="ثبت" class="btn btn-success" />

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Jordan/Areas/Admin/Views/Feature/Edit.cshtml
@model Domain.Store.Feature
@{
   
}
<div class="col-md-12">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">ویرایش دسته بندی</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class=" col-lg-12 col-md-4">
                    <form asp-action="Edit" enctype="multipart/form-data" id="myform">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            
                            <label asp-for="subCategoryId" class="control-label"></label>
                            <select asp-for="subCategoryId" class="form-control" asp-items="ViewBag.SubCategory"></select>
                            <span asp-validation-for="subCategoryId" class="text-danger"></span>

                        </div>
                      
                        <div class="form-group">
                            <input type="submit" value="ثبت" class="btn btn-info" />


                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>

Jordan/Areas/Admin/Views/Feature/Index.cshtml
@model IEnumerable<Domain.Store.Feature>
@{
    ViewData["Title"] = "Index";
}


<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title"> دسته بندی بر اساس </h3>
        </div>
        <div class="card-body">
            <p>
                <a class="btn btn-success" asp-action="Create">جدید</a>
            </p>
            <table class="table table-responsive table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.subCategorycategory.SubCategoryName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Title)
                        </th>
                      
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.subCategorycategory.SubCategoryName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>

                          
                            <td>
                                <a class="btn btn-info" asp-action="Edit" asp-route-FeatureId="@item.Id">ویرایش</a>
                                <a class="btn btn-danger" asp-action="delete" onclick="return confirm('ایا از حذف اطمینان دارید؟')" asp-route-id="@item.Id">حذف</a>
                                <a class="btn btn-primary" asp-action="Index" asp-controller="FeatureValue" asp-route-FeatureId="@item.Id">زیر دسته ها</a>


                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>